apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fib-calc-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # Since the tls section has been commented out and we rely on the wildcard certificate this is not needed anymore
    #cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  # Leaving this here will issue a new tls certificate for fib-calc.dotnet-works.com
  # By leaving is out we can use the generic Ingress configuration and default TLS certificate for *.dotnet-works.com
  # See the k8s/certs repo 
  # tls:
  #   - hosts:
  #       - fib-calc.dotnet-works.com
  #     secretName: fib-calc-dotnet-works-com-tls
  rules:
    - host: fib-calc.dotnet-works.com
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000