name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: dnw2022
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker build -t react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true react-test npm test

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ env.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build images
        run: |
          docker build -t dnw2022/fib-calc-client ./client
          docker build -t dnw2022/fib-calc-server ./server
          docker build -t dnw2022/fib-calc-worker ./worker
          docker build -t dnw2022/fib-calc-nginx ./nginx

      - name: Push images to docker hub
        run: |
          docker push dnw2022/fib-calc-client
          docker push dnw2022/fib-calc-server
          docker push dnw2022/fib-calc-worker
          docker push dnw2022/fib-calc-nginx

      # Instead of building and pushing the images to docker hub, we can just pass the docker-compose.yml to AWS elastic beanstalk
      # and let it create a multi-container environment. We just push a zip file with all the deployment stuff to our S3 bucket and 
      # AWS will use it to trigger an update of our environment
      # 
      # See: https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/20695748#questions

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-react
      #     environment_name: Dockerreact-env
      #     existing_bucket_name: elasticbeanstalk-eu-central-1-334920449303
      #     region: eu-central-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip